Error contacting Ollama API: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f888019ede0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Forecast

10: 35.0
20: 40.0
40: 45.0
60: 50.0
80: 55.0
90: 60.0
11: 35.5
12: 36.0
13: 36.5
14: 37.0
15: 37.5
16: 38.0
17: 38.5
18: 39.0
19: 39.5
21: 40.25
22: 40.5
23: 40.75
24: 41.0
25: 41.25
26: 41.5
27: 41.75
28: 42.0
29: 42.25
30: 42.5
31: 42.75
32: 43.0
33: 43.25
34: 43.5
35: 43.75
36: 44.0
37: 44.25
38: 44.5
39: 44.75
41: 45.25
42: 45.5
43: 45.75
44: 46.0
45: 46.25
46: 46.5
47: 46.75
48: 47.0
49: 47.25
50: 47.5
51: 47.75
52: 48.0
53: 48.25
54: 48.5
55: 48.75
56: 49.0
57: 49.25
58: 49.5
59: 49.75
61: 50.25
62: 50.5
63: 50.75
64: 51.0
65: 51.25
66: 51.5
67: 51.75
68: 52.0
69: 52.25
70: 52.5
71: 52.75
72: 53.0
73: 53.25
74: 53.5
75: 53.75
76: 54.0
77: 54.25
78: 54.5
79: 54.75
81: 55.5
82: 56.0
83: 56.5
84: 57.0
85: 57.5
86: 58.0
87: 58.5
88: 59.0
89: 59.5